Add option to restore old settings after shutdown/reboot/logout

diff --git a/.local/bin/my_scripts/change-font b/.local/bin/my_scripts/change-font
--- a/.local/bin/my_scripts/change-font
+++ b/.local/bin/my_scripts/change-font
@@ -1,28 +1,41 @@
 #!/bin/sh
 
+# store font name here
+CACHE_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/x-font"
 # list of fonts
 ALLFONTS=$(grep "^! " "${XDG_CONFIG_HOME}/X11/fontprofiles" | sed 's/^..//g')
 
-# use command-line arg or get font using dmenu prompt
-SELFONT=${*:-"$(echo "$ALLFONTS" | sort | dmenu -i -l 30 -p "Select Font")"}
-
-if echo "$ALLFONTS" | grep -q "^${SELFONT}$"
-then
-	# merge, to only overwrite colors but preserve font data
-	grep "^! ${SELFONT}$" -A3 "${XDG_CONFIG_HOME}/X11/fontprofiles" | xrdb -merge
- 
-	# send USR1 signal to all running st instances
-	# shellcheck disable=SC2046
- 	kill -s USR1 $(pidof st)
- 
-	# restart dwm using this hack
-	xdotool key "Super+F12"
- 
-	# restart dunst, this script internally handles colors from xresources
- 	restart-dunst
- 
-	# send notification only if command started with dmenu and NOT command-line args
- 	[ -z "$*" ] && notify-send "Font set to ${SELFONT}"
+if [ "$1" = "--restore" ] && [ -z "$2" ] ; then
+	# take font from cache file if `--restore` passed
+	CHOOSEN_FONT=$(cat "$CACHE_FILE" 2>/dev/null)
+elif [ -z "$1" ] ; then
+	# choose font using dmenu if no args passed
+	CHOOSEN_FONT=$(echo "$ALLFONTS" | dmenu -i -l 30 -p "Choose font")
+	# exit if nothing choosen
+	[ -z "$CHOOSEN_FONT" ] && exit
+elif [ -n "$1" ] && [ -z "$2" ] ; then
+	# use first arg as font name
+	CHOOSEN_FONT="$1"
 else
-	exit 1
+	1>&2 echo "Invalid useage" && exit 1
 fi
+
+echo "$ALLFONTS" | grep "^${CHOOSEN_FONT}$" -q || CHOOSEN_FONT="DejaVu Sans Mono"
+
+echo "$CHOOSEN_FONT" > "$CACHE_FILE"
+
+# merge, to only overwrite colors but preserve font data
+grep "^! ${CHOOSEN_FONT}$" -A3 "${XDG_CONFIG_HOME}/X11/fontprofiles" | xrdb -merge
+
+# send USR1 signal to all running st instances
+# shellcheck disable=SC2046
+kill -s USR1 $(pidof st)
+
+# restart dwm using this hack
+xdotool key "Super+F12"
+
+# restart dunst, this script internally handles colors from xresources
+restart-dunst
+
+# send notification only if command started with dmenu and NOT command-line args
+[ -z "$*" ] && notify-send "Font set to ${CHOOSEN_FONT}"
diff --git a/.local/bin/my_scripts/change-mode b/.local/bin/my_scripts/change-mode
--- a/.local/bin/my_scripts/change-mode
+++ b/.local/bin/my_scripts/change-mode
@@ -1,10 +1,30 @@
 #!/bin/sh
 
+# store theme name here
+CACHE_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/x-theme"
 # list of themes
 THEMES="$(flavours list | tr ' ' '\n')"
 
-# use command-line arg or get theme using dmenu prompt
-CHOOSEN_THEME=${*:-"$(echo "$THEMES" | dmenu -i -l 30 -p "Choose theme")"}
+if [ "$1" = "--restore" ] && [ -z "$2" ] ; then
+	# take theme from cache file if `--restore` passed
+	CHOOSEN_THEME=$(cat "$CACHE_FILE" 2>/dev/null)
+elif [ -z "$1" ] ; then
+	# choose theme using dmenu if no args passed
+	CHOOSEN_THEME=$(echo "$THEMES" | dmenu -i -l 30 -p "Choose theme")
+	# exit if nothing choosen
+	[ -z "$CHOOSEN_THEME" ] && exit
+elif [ -n "$1" ] && [ -z "$2" ] ; then
+	# use first arg as theme if passed
+	CHOOSEN_THEME="$1"
+else
+	1>&2 echo "Invalid useage" && exit
+fi
+
+# use gruvbox-dark-hard if theme is invalid
+echo "${THEMES}" | grep "^$CHOOSEN_THEME$" -q || CHOOSEN_THEME="gruvbox-dark-hard"
+
+# write theme to cache file
+echo "$CHOOSEN_THEME" > "$CACHE_FILE"
 
 # try to apply theme and send notification only if command started with dmenu and NOT command-line args
 flavours apply "$CHOOSEN_THEME" && [ -z "$*" ] && notify-send "Theme set to ${CHOOSEN_THEME}"
